### PR TITLE
feat: migrate to new mdx package

### PR DESCRIPTION
**Pull request by rpmccarter**
We're attempting to migrate from the pages router to the app router in our main project. Unfortunately, `next-mdx-remote` does not play nicely with newer versions of the app router (see [this issue](https://github.com/hashicorp/next-mdx-remote/issues/480)). To move forward, we're migrating from `next-mdx-remote` to `next-mdx-remote-client`, a fork of `next-mdx-remote` that is actively maintained and has a better API

When testing this, I ran into a huge host of issues attempting to test the example projects. I reckoned with God. As a result, I also decided to migrate the repo to a Yarn v4 workspace in this PR. Excitingly, the example projects appear to be working with the version of @mintlify/mdx in the codebase!

### CODE REVIEW

**Comment by hahnbeelee** [comment]
can u update the readme outlining the new api?

**Comment by rpmccarter** [comment]
@hahnbeelee updated readmes!

**Review by hahnbeelee — APPROVED** [review]
LGTM

**Comment by talatkuyuk** [comment]
As the author, I'm glad to see that Mintlify is using **`next-mdx-remote-client`** under the hood. 👏👏👏

**Pull request merged**
